apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod1
  labels:
    name: voting-app-pod1
    app: demo-voting-app1
spec:
  containers:
  - name: voting-app1
    image: shantanusohni/reactjs
    ports:
         - containerPort: 80